
## MySQL Configuration
spring:
  datasource:
    url: jdbc:mysql://172.17.0.15:3306/coredb?useSSL=false
    username: myuser
    password: mypwd
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        use_sql_comments: true
        format_sql: true

springdoc:
  swagger-ui:
    path: /shasr.html
    operationsSorter: method